# Generated by Django 4.1.7 on 2023-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0005_alter_medicine_contradictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.URLField(),
        ),
    ]
