# Generated by Django 4.1.7 on 2023-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalinfo', '0006_alter_doctor_image_alter_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='False', max_length=254),
        ),
    ]
